server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: studyhub-api

  servlet:
    multipart:
      max-file-size: 500MB       # Giới hạn 1 file (default: 1MB)
      max-request-size: 510MB    # Giới hạn toàn bộ request (default: 10MB)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/study_hub}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:abc123!}

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  task:
    scheduling:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:defaulupt}
      database: 0

jwt:
  signer-key: ${SIGNER_KEY:pPj043gpT9GBlty/YK2W/DsMS0yivBosos6VzXtelJUjkN97X0yQGZnF7sToVIlH}
  valid-duration: 7200 #in seconds
  refreshable-duration: 72000 #in seconds

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}

open:
  api:
    title: studyhub-api document
    version: v0.0.1
    serverUrl: http://localhost:8080/api/v1
    serverName: Server Dev

payos:
  client-id: ${PAYOS_CLIENT_ID:StudyHub}
  api-key: ${PAYOS_API_KEY:StudyHub}
  checksum-key: ${PAYOS_CHECKSUM_KEY:StudyHub}
  url-return: http://localhost:4200//hoc-vien/trang-chu

mailtoken: ${MAIL_TOKEN}